[package]
name = "brainfucke-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
cc = { version = "1.0", optional = true }
crossterm = { version = "0.13", optional = true }

[features]
default = ["cc"]
cc = ["dep:cc"]
raw-mode = ["dep:crossterm"] # CURRENTLY BROKEN